import { z } from "zod";
declare const configSchema: z.ZodObject<{
    APP_ENV: z.ZodDefault<z.ZodEnum<["development", "test", "staging", "production"]>>;
    APP_BASE_URL: z.ZodDefault<z.ZodString>;
    APP_TRUSTED_PROXY: z.ZodDefault<z.ZodEffects<z.ZodOptional<z.ZodUnion<[z.ZodBoolean, z.ZodString]>>, boolean, string | boolean | undefined>>;
    LOG_LEVEL: z.ZodDefault<z.ZodEnum<["debug", "info", "warn", "error"]>>;
    DATABASE_URL: z.ZodString;
    REDIS_URL: z.ZodString;
    S3_ENDPOINT: z.ZodString;
    S3_REGION: z.ZodDefault<z.ZodString>;
    S3_ACCESS_KEY: z.ZodString;
    S3_SECRET_KEY: z.ZodString;
    S3_BUCKET_UPLOADS: z.ZodString;
    S3_BUCKET_EXPORTS: z.ZodString;
    S3_BUCKET_ARTIFACTS: z.ZodString;
    S3_FORCE_PATH_STYLE: z.ZodDefault<z.ZodEffects<z.ZodOptional<z.ZodUnion<[z.ZodBoolean, z.ZodString]>>, boolean, string | boolean | undefined>>;
    COOKIE_SECURE: z.ZodDefault<z.ZodEffects<z.ZodOptional<z.ZodUnion<[z.ZodBoolean, z.ZodString]>>, boolean, string | boolean | undefined>>;
    ACCESS_TOKEN_TTL_SECONDS: z.ZodDefault<z.ZodNumber>;
    REFRESH_TOKEN_TTL_SECONDS: z.ZodDefault<z.ZodNumber>;
    BREAK_GLASS_ACCESS_TOKEN_TTL_SECONDS: z.ZodDefault<z.ZodNumber>;
    PASSWORD_RESET_TOKEN_TTL_SECONDS: z.ZodDefault<z.ZodNumber>;
    INVITE_TOKEN_TTL_SECONDS: z.ZodDefault<z.ZodNumber>;
    BOOTSTRAP_TOKEN: z.ZodString;
    ENCRYPTION_KEY_BASE64: z.ZodString;
    JWT_SECRET: z.ZodString;
    WORKER_CONCURRENCY: z.ZodDefault<z.ZodNumber>;
    MAX_UPLOAD_BYTES: z.ZodDefault<z.ZodNumber>;
    RATE_LIMIT_AUTH_PER_MINUTE: z.ZodDefault<z.ZodNumber>;
    RATE_LIMIT_CHAT_PER_MINUTE: z.ZodDefault<z.ZodNumber>;
    EMAIL_PROVIDER: z.ZodDefault<z.ZodEnum<["manual", "resend", "smtp"]>>;
    RESEND_API_KEY: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    EMAIL_FROM: z.ZodDefault<z.ZodOptional<z.ZodString>>;
}, "strip", z.ZodTypeAny, {
    APP_ENV: "development" | "test" | "staging" | "production";
    APP_BASE_URL: string;
    APP_TRUSTED_PROXY: boolean;
    LOG_LEVEL: "debug" | "info" | "warn" | "error";
    DATABASE_URL: string;
    REDIS_URL: string;
    S3_ENDPOINT: string;
    S3_REGION: string;
    S3_ACCESS_KEY: string;
    S3_SECRET_KEY: string;
    S3_BUCKET_UPLOADS: string;
    S3_BUCKET_EXPORTS: string;
    S3_BUCKET_ARTIFACTS: string;
    S3_FORCE_PATH_STYLE: boolean;
    COOKIE_SECURE: boolean;
    ACCESS_TOKEN_TTL_SECONDS: number;
    REFRESH_TOKEN_TTL_SECONDS: number;
    BREAK_GLASS_ACCESS_TOKEN_TTL_SECONDS: number;
    PASSWORD_RESET_TOKEN_TTL_SECONDS: number;
    INVITE_TOKEN_TTL_SECONDS: number;
    BOOTSTRAP_TOKEN: string;
    ENCRYPTION_KEY_BASE64: string;
    JWT_SECRET: string;
    WORKER_CONCURRENCY: number;
    MAX_UPLOAD_BYTES: number;
    RATE_LIMIT_AUTH_PER_MINUTE: number;
    RATE_LIMIT_CHAT_PER_MINUTE: number;
    EMAIL_PROVIDER: "manual" | "resend" | "smtp";
    RESEND_API_KEY: string;
    EMAIL_FROM: string;
}, {
    DATABASE_URL: string;
    REDIS_URL: string;
    S3_ENDPOINT: string;
    S3_ACCESS_KEY: string;
    S3_SECRET_KEY: string;
    S3_BUCKET_UPLOADS: string;
    S3_BUCKET_EXPORTS: string;
    S3_BUCKET_ARTIFACTS: string;
    BOOTSTRAP_TOKEN: string;
    ENCRYPTION_KEY_BASE64: string;
    JWT_SECRET: string;
    APP_ENV?: "development" | "test" | "staging" | "production" | undefined;
    APP_BASE_URL?: string | undefined;
    APP_TRUSTED_PROXY?: string | boolean | undefined;
    LOG_LEVEL?: "debug" | "info" | "warn" | "error" | undefined;
    S3_REGION?: string | undefined;
    S3_FORCE_PATH_STYLE?: string | boolean | undefined;
    COOKIE_SECURE?: string | boolean | undefined;
    ACCESS_TOKEN_TTL_SECONDS?: number | undefined;
    REFRESH_TOKEN_TTL_SECONDS?: number | undefined;
    BREAK_GLASS_ACCESS_TOKEN_TTL_SECONDS?: number | undefined;
    PASSWORD_RESET_TOKEN_TTL_SECONDS?: number | undefined;
    INVITE_TOKEN_TTL_SECONDS?: number | undefined;
    WORKER_CONCURRENCY?: number | undefined;
    MAX_UPLOAD_BYTES?: number | undefined;
    RATE_LIMIT_AUTH_PER_MINUTE?: number | undefined;
    RATE_LIMIT_CHAT_PER_MINUTE?: number | undefined;
    EMAIL_PROVIDER?: "manual" | "resend" | "smtp" | undefined;
    RESEND_API_KEY?: string | undefined;
    EMAIL_FROM?: string | undefined;
}>;
export type PacketChatConfig = z.infer<typeof configSchema>;
export declare function getConfig(env?: NodeJS.ProcessEnv): PacketChatConfig;
export declare function isProduction(config?: {
    APP_ENV: "development" | "test" | "staging" | "production";
    APP_BASE_URL: string;
    APP_TRUSTED_PROXY: boolean;
    LOG_LEVEL: "debug" | "info" | "warn" | "error";
    DATABASE_URL: string;
    REDIS_URL: string;
    S3_ENDPOINT: string;
    S3_REGION: string;
    S3_ACCESS_KEY: string;
    S3_SECRET_KEY: string;
    S3_BUCKET_UPLOADS: string;
    S3_BUCKET_EXPORTS: string;
    S3_BUCKET_ARTIFACTS: string;
    S3_FORCE_PATH_STYLE: boolean;
    COOKIE_SECURE: boolean;
    ACCESS_TOKEN_TTL_SECONDS: number;
    REFRESH_TOKEN_TTL_SECONDS: number;
    BREAK_GLASS_ACCESS_TOKEN_TTL_SECONDS: number;
    PASSWORD_RESET_TOKEN_TTL_SECONDS: number;
    INVITE_TOKEN_TTL_SECONDS: number;
    BOOTSTRAP_TOKEN: string;
    ENCRYPTION_KEY_BASE64: string;
    JWT_SECRET: string;
    WORKER_CONCURRENCY: number;
    MAX_UPLOAD_BYTES: number;
    RATE_LIMIT_AUTH_PER_MINUTE: number;
    RATE_LIMIT_CHAT_PER_MINUTE: number;
    EMAIL_PROVIDER: "manual" | "resend" | "smtp";
    RESEND_API_KEY: string;
    EMAIL_FROM: string;
}): boolean;
export {};
//# sourceMappingURL=index.d.ts.map